# Generated by Django 5.2.5 on 2025-09-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.BigIntegerField(unique=True, verbose_name='Внутреннее id encar')),
                ('url', models.URLField()),
                ('inspection', models.BooleanField(default=False)),
                ('record', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('photo_url', models.CharField(max_length=256)),
                ('photos_codes', models.CharField(blank=True, max_length=512, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.CharField(blank=True, max_length=128, null=True)),
                ('version_details', models.CharField(blank=True, max_length=128, null=True)),
                ('color', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('engine_capacity', models.IntegerField(blank=True, db_index=True, null=True)),
                ('transmission', models.CharField(db_index=True, max_length=128)),
                ('fuel_type', models.CharField(choices=[('G', 'Бензин'), ('D', 'Дизель'), ('L', 'Газ'), ('GE', 'Бензин + Электро'), ('DE', 'Дизель + Электро'), ('LE', 'Газ + Электро'), ('LG', 'Газ + Бензин'), ('E', 'Электро'), ('HY', 'Водород')], db_index=True, default='G', max_length=2)),
                ('release_date', models.IntegerField(db_index=True)),
                ('model_year', models.IntegerField()),
                ('mileage', models.IntegerField(db_index=True)),
                ('options', models.CharField(blank=True, max_length=1024, null=True)),
                ('price', models.BigIntegerField()),
                ('ru_price', models.IntegerField(blank=True, null=True)),
                ('customs_duty', models.IntegerField(blank=True, null=True)),
                ('recycling_fee', models.IntegerField(blank=True, null=True)),
                ('sell_type', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
                ('city', models.CharField(max_length=128)),
                ('korean_number', models.CharField(blank=True, max_length=32, null=True)),
                ('dummy_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('encar_diag', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('vechile', models.CharField(choices=[('CAR', 'CAR'), ('TRUCK', 'TRUCK')], default='TRUCK', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.BigIntegerField(unique=True, verbose_name='Внутреннее id encar')),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=1)),
                ('trust_service', models.CharField(max_length=50)),
                ('inspection', models.BooleanField(default=False)),
                ('record', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('photo_url', models.CharField(max_length=256)),
                ('photos_codes', models.CharField(blank=True, max_length=512, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('version', models.CharField(blank=True, max_length=128, null=True)),
                ('version_details', models.CharField(blank=True, max_length=128, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('engine_capacity', models.IntegerField(blank=True, null=True)),
                ('horse_power', models.IntegerField(blank=True, null=True)),
                ('capacity', models.CharField(max_length=32)),
                ('transmission', models.CharField(max_length=128)),
                ('fuel_type', models.CharField(choices=[('G', 'Бензин'), ('D', 'Дизель'), ('L', 'Газ'), ('GE', 'Бензин + Электро'), ('DE', 'Дизель + Электро'), ('LE', 'Газ + Электро'), ('LG', 'Газ + Бензин'), ('E', 'Электро'), ('HY', 'Водород')], default='G', max_length=2)),
                ('release_date', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('options', models.CharField(blank=True, max_length=1024, null=True)),
                ('price', models.BigIntegerField()),
                ('usage', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
                ('city', models.CharField(max_length=128)),
                ('korean_number', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_count', models.IntegerField()),
                ('other_accident_cost', models.IntegerField(default=0)),
                ('other_accident_count', models.IntegerField(default=0)),
                ('driver_accident_cost', models.IntegerField(default=0)),
                ('driver_accident_count', models.IntegerField(default=0)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_record', to='parser.car')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_accident', models.CharField(choices=[('1', 'Урегулировано страховой владельца данного авто'), ('2', 'Возмещение за счет страховой виновника'), ('3', 'С ущербом чужому здоровью или имуществу')], max_length=1)),
                ('date', models.DateField()),
                ('insurance_benefit', models.IntegerField(default=0)),
                ('part_cost', models.IntegerField(default=0)),
                ('labor_cost', models.IntegerField(default=0)),
                ('painting_cost', models.IntegerField(default=0)),
                ('car_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.carrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_front_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('left_back_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('right_front_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('right_back_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('trunk', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('hood', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('front_fender_right', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('front_fender_left', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='parser.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.optioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='TruckOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.optioncategory')),
            ],
        ),
    ]
